### ISSUE TITLE
Switching video input from desktop to "none" crashes

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#210]
1. start utox
2. go to A/V settings
3. switch to desktop input
4. switch to "none" input

```
stopped video
uToxVID:	Changed video input device
uToxVID:	Changed video input device
uToxVID:	Changed video input to NONE
*** Error in `/home/cebe/dev/tox/uTox/utox': double free or corruption (out): 0x00007fffd8000f00 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe73c8700 (LWP 1595)]
0x00007ffff4ce8067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff4ce8067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4ce9448 in __GI_abort () at abort.c:89
#2  0x00007ffff4d261b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff4e1b820 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff4d2b98e in malloc_printerr (action=1, str=0x7ffff4e1b970 "double free or corruption (out)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff4d2c696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff6e7ad31 in vpx_img_free () from /usr/lib/x86_64-linux-gnu/libvpx.so.1
#6  0x00000000004075b9 in closevideodevice (handle=0x1) at src/video.c:21
#7  0x000000000040770a in utox_video_record_stop (preview=false) at src/video.c:83
#8  0x00000000004075e2 in utox_video_change_device (device=0x0) at src/video.c:30
#9  0x00000000004b5323 in utox_av_ctrl_thread (args=0x7fffe00a3a80) at src/utox_av.c:205
#10 0x00007ffff63ca0a4 in start_thread (arg=0x7fffe73c8700) at pthread_create.c:309
#11 0x00007ffff4d9b87d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by GrayHatter** [comment]
fixed in develop @cebe

**Comment by cebe** [comment]
at least the crash is gone. I am however still able to get viedo preview into a situation where the button thinks preview is running, when it is actually not. Meaning I can not start a new preview because clicking the button tries to stop a not running preview...

**Comment by cebe** [comment]
reproduced. new issue: #221
